### ISSUE TITLE
Webseite aktualisieren

### ISSUE THREAD

**Issue by Erdnaf** [FUB-HCC/20-SWP-CodingOpenness#216]
# Bounty

## Scope

- Einbinden des Prototyps + Beschreibung @julizet 
- Textanpassung @Erdanf 
- How to Implement Anleitung @linuxhelf 
- Recherche Findings (wie bereitet man Data Privacy Information ordentliche auf) UND Aktivitäten in dem offiziellen Repo @molpremotone & @kraleva (bitte selbstständig einteilen)

## Deliverables

- siehe oben --> eine zusammenhängende Übersicht, über unsere Teamleistung 

## Gain for the project

- Anpassung der Website:  https://fub-hcc.github.io/20-SWP-CodingOpenness/corona-warn-app

## Roles

bounty worker: @julizet  @Erdanf @linuxhelf @molpremotone @kraleva 
review erfolgt am Dienstag im Meeting

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by julizet** [comment]
Bitte die Fortschritte in die Kommentare hier posten.
Habe die Beschreibung angepasst, damit die Aufgaben klar verteilt sind

**Comment by Erdnaf** [comment]
Ich hab einen Entwurf für die Webseite gemacht und dabei die Rechtschreibfehler berichtigt und den Prototypen eingebunden (siehe PR #219 )
Die Änderungen können auf dem Branch `website/feat/cwa-privacy` angeschaut werden

**Comment by Erdnaf** [comment]
Ich denke direkt auf der Webseite zu arbeiten ist bei den ganzen Themen wahrscheinlich nicht so sinvoll, da wir doch ziemlich viel Inhalt haben. Was haltet ihr von einer Wikipage, wo wir das niederschreiben und die wir dann verlinken?
Die könnten wir auch in der Abschlusspräsentation (#217) verwenden, damit wir uns nicht doppelte Arbeit machen

**Comment by kraleva** [comment]
Ich werde die Recherche-Findings beschreiben ,wobei ich auch Informationen von unserem Vergleich der Ansatze verbinden werde. @molpremotone  dann willst du die Beschreibung der Aktivitaten im offiziellen Repo ubernehmen? Ich dachte, dass es auch eine gute Idee waere, dass wir die Data Privacy Tabelle aus dem Vergleich der Anstaetze in der Recherchebeschreibung hinzufuegen. Was denkt ihr daran ? Wir waren quazi fast dieselben Menschen in der Gruppe "Vergleich" so ich glaube es waere kein Problem aus dem Grund, dass wir eigentlich die Tabelle vorbereitet haben ?

**Comment by kraleva** [comment]
Mein Vorschlag für die Recherche als Markdown. Wenn es Verbesserungsvorschläge gibt, bitte hier schreiben. Nach Abstimmung, kann ich dieses sollte dieses Markdown auch in der Webseite fließen. 

## Data-Privacy Research

### Recherche
1. **Anforderungen an dem App recherchieren**
   
   Wir haben uns erstmal mit den drei möglichen Ansätzen zur Entwurf und Verwirklichung eines solchen Apps beschäftigt. Damals, war das offizielle App Repository fast leer, das einzige, was zur Verfügung gestellt war, war die Dokumentation. Wir wussten schon, dass es drei Konzepte zur Implementierung gab, nämlich :  
    * [PEPP PT](https://github.com/pepp-pt/pepp-pt-documentation/blob/master/10-data-protection/PEPP-PT-data-protection-information-security-architecture-Germany.pdf)
    * [DP-3T](https://github.com/DP-3T/documents/blob/master/DP3T%20White%20Paper.pdf)
    * [DCTS](https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki/Vergleich-der-Ans%C3%A4tze%3A-Digital-Contact-Tracing-Service-%28DCTS%29)
  
    Wir wussten schon damals, dass der gewählte Ansatz zur Verwirklichung DP-3T war, trotzdem hat die gegebene Dokumentation nicht so detailiert das Erreichen einiger Datenschutz und Sicherheit Aspekten beschrieben. 
    Wir haben die Dokumentation der drei Ansätzen gelesen und dann sollten wir die Verschiedenen Aspekten der Ansätze vergleichen (die jeweilige Dokumentation ist als Hyperlinks in der obengegebene Liste verlinkt).
    Demnächst haben wir mehrere Tabellen zu dem Vergleich der Ansätze vorbereitet. Dazu haben wir auch die Konzepte bezüglich ihrem Datenschutz und Sicherheit verglichen.

    [Hier](https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki/Vergleich-der-Ans%C3%A4tze) kann man die ganze Recherche, die wir mithilfe einiger unserer Komillitonen von den anderen Teams gemacht haben.

    Unsere Tabellen zum Vergleich der Datenschutzaspekt und die Transperenz: 

    ## Privatsphäre und Transparenz
    ### Allgemein
    | Kriterium  | PEPP-PT      | DP3T         | DCTS          | Corona Warn App |
    | -----------| -------------| -------------| -------------| -------------|
    | <b>Welche Daten sieht der Server-Betreiber</b> | <details><summary><b>User-IDs und Push-ID + Status (Infiziert/Kontakt)</b></summary>Der Status Infiziert/ Kontakt mit Infiziertem ist nur bekannt, falls der Infizierte ihn hochgeladen hat.</details> | <details><summary><b>Seeds infizierter Nutzer</b></summary>Nach Bestätigung durch den Arzt läd der Infizierte seine Seeds hoch.</details> | <details><summary><b>BLE-IDs infizierter Nutzer + Zweitkontakte</b></summary>Nach Bestätigung durch Arzt kann der Infizierte seine BLE-IDs hochladen. Wenn ein Kontakt mit einem Infizierten bestand, kann der Nutzer entscheiden auch seine BLE-IDs als "potenziell infiziert" hochzuladen.</details> | <details><summary><b>Seeds infizierter Nutzer</b></summary>Nach Bestätigung durch den Arzt läd der Infizierte seine Seeds hoch.</details> |
    | <b>Welche Daten sieht die App</b>  | <b> BLE-IDs (eigene + Kontakte)</b> | <details><summary><b>Seed, BLE-IDs (eigene + Kontakte)</b></summary>Aus dem Seed, der jeden Tag gewechselt wird, werden BLE-IDs erzeugt werden.</details> | <details><summary><b>Seed, BLE-IDs (eigene + Kontakte)</b></summary>Der Temporäre Seed wird täglich gewechselt, daraus werden die BLE-IDs erstellt, die ausgetauscht werden.</details> |<details><summary><b>Seeds infizierter Nutzer</b></summary>Die App erhält die Seeds infizierter Nutzer vom Server. Die BLE-IDs sind in Framework von Apple/Google versteckt und die App/der Nutzer hat keinen Zugriff.</details> |
    | <details><summary><b>Wie lange werden die Daten gespeichert</b></summary>Die Datenspeicherung auf dem Server kann der Nutzer nicht prüfen, aber lokale Daten könnten z.b. per modifizierter App regelmäßig gelöscht werden.</details>| <b>keine Angabe</b> | <b>keine Angabe</b> | <details><summary><b>2-3 Wochen</b></summary>Ausgehend von der möglichen Inkubationszeit. Kann angepasst werden.</details> | <b>14 Tage</b>  |
    | <details><summary><b>Wer entscheidet über Datenübertragung bei Infektion?</b></summary>siehe auch Bestätigung der Infizierung</details>  | <b>Infizierter nach Authorisierung</b> | <b>Infizierter nach Authorisierung</b> | <b>Infizierter nach Authorisierung</b> | <b>Infizierter nach Authorisierung</b> |
    | <details><summary><b>Wer entscheidet über Datenübertragung bei Kontakt mit Infiziertem?</b></summary>bei DCTS für Zweitkontaktverfolgung</details>  | <details><summary><b>Infizierter nach Authorisierung</b></summary>Der Infizierte lädt seine Kontakte hoch, dies ist nicht optional wenn man sich für hochladen entscheidet.</details> | <b>Daten werden nicht erhoben</b> | <details><summary><b>Kontaktperson entscheidet</b></summary>Wenn man Kontakt mit einer infizierten Person hatte, so wird man darüber informiert und hat die Option seine eigenen IDs hochzuladen (siehe Zweitkontaktverfolgung)</details> |<b>Daten werden nicht erhoben</b> |
    | <b>Haltung gegenüber Open Source</b>  |<details><summary><b>negativ</b></summary>Wird vorgeworfen, nicht nach Transparenz zu streben.</details>| <b>Abspaltung von PEPP-PT</b> | <b>Unterstützt komplett Open-Source</b> | <details><summary><b>positiv</b></summary>Quelltext von Client uns Server werden successive veröffentlicht</details>

    ### Identität
    | Kriterium  | PEPP-PT      | DP3T         | DCTS          | Corona Warn App |
    | -----------| -------------| -------------| -------------| -------------|
    | <details><summary><b>Pseudo- / Anonymisierung</b></summary></details>  | <details><summary><b>Pseudonymisierung</b></summary>die User-ID ist permanent und auf Server gespeichert, damit + Push-Notification-ID ist eine Identifikation möglich</details> | <details><summary><b>Anonymisierung</b></summary>der Seed ist der einzige konstante und zur Identifikation nutzbare Datenwert, dieser ändert sich jedoch täglich und wird dem Server nur bei Infizierung bekanntgegeben</details> | <details><summary><b>Anonymisierung</b></summary>der Seed ist der einzige konstante und zur Identifikation nutzbare Datenwert, dieser ändert sich jedoch täglich und wird dem Server nur bei Infizierung bekanntgegeben</details> | <details><summary><b>Anonymisierung</b></summary>Authentifizierung zum Upload der Keys geschieht nur durch eine TAN, die auf Serverseite gelöscht wird</details>
    | <details><summary><b>Wer kann aus der BLE-ID eine User-ID zurückrechnen?</b></summary></details>  | <details><summary><b>Server</b></summary>Die BLE-ID ist eine symmetrisch verschlüsselte User-ID</details> | <details><summary><b>es gibt keine User-ID</b></summary> und die Seeds sind nicht zurückrechenbar</details> | <details><summary><b>es gibt keine User-ID</b></summary> und die Seeds sind nicht zurückrechenbar</details> | <details><summary><b>es gibt keine User-ID</b></summary> und die Seeds sind nicht zurückrechenbar</details>
    | <details><summary><b>Identifizierung der App-User durch Server (Zuweisung von ID's)</b></summary>Die Zuweisung und Anzahl der temporären und nichttemporären ID's und die Methode, die auf dem Server angewendet wird, um den Benutzern ihre Appdaten zuweisen zu können, ohne die als Person indefizieren zu können.</details>  | <details><summary><b>1 User-ID/mehrere BLE-IDs/ein Push-ID</b></summary>Der Nutzer bekommt eine einzigartige User-ID (Permanent pseudonym of the app), womit er auf dem Backend indentifizert werden kann, die Push-ID wird nur auf dem Backend gespeichert. Dazu bekommt der Nutzer auch mehrere BLE-ID, die er bei dem BLE-Broadcasting schickt, zusammen mit einem Timestamp, sodass er danach mithilfe dieser BLE-ID und dem Timestamp auf dem Server indentifiziert werden kann und von dem Push-Notification Service mit Hilfe seiner Push-ID benachrichtigt werden kann. Der Nutzer bekommt niemals sein User-ID, aber die BLE-IDs werden ihm zugeteilt und zur Nutzung für einem bestimmten Zeitraum gestellt, danach werden neue BLE-IDs für den selben Nutzer vom Server erstellt (bei vorhandener Internetverbindung) und das widerholt sich, sodass es nicht möglich ist, dass der Nutzer von anderen Nutzer mithilfe des BLE-IDs indentifizert wird.  </details> | <details><summary><b>Nein</b></summary>Die BLE-IDs werden nicht vom Server generiert bzw. wenn der Server die erhält, ist schon eine neuer Seed auf der Userapp generiert worden</details> | <details><summary><b>Nein</b></summary>Die BLE-IDs werden nicht vom Server generiert bzw. wenn der Server die erhält, ist schon eine neuer Seed auf der Userapp generiert worden. Beim Abfragen der infizierten ID's hat eine App jedes mal eine andere ID, ist also vom Server aus nicht zu identifizieren</details> | <details><summary><b>Nein</b></summary>Authentifizierung zum Upload der Keys geschieht nur durch eine TAN, die auf Serverseite gelöscht wird</details>
    | <b>Kontakt-Graph-Generierung möglich</b>  | <details><summary><b>ja</b></summary>Alle Nutzer haben permanente User-IDs, bei hochladen der Infizerung kennt der Server die permanten User-IDs der Infizierten + aller seiner Kontakte</details> | <details><summary><b>Nein</b></summary>weil nur eigene IDs hochgeladen werden.</details> | <details><summary><b>Nein</b></summary>weil nur eigene IDs hochgeladen werden. Bei Zweit-Kontakt-Verfolgung wird durch Zero-Knowledge-Proof verhindert, dass Rückschlüsse auf den Begeneten Infizierten gemacht werden können. </details> | <details><summary><b>Nein</b></summary></details>

    Wir haben auch dazu noch die offene Frage gestellt, was man noch zu der Privatsphäre und Transperenz Tabelle als Anforderung und Vergleichspunkten noch hinzufügen könnte. Dafür haben wir ein Email an einigen Professoren (Expertenpanel) geschickt mit der Bitte, dass die uns da beibringen. Den beschriebenen Umgang damit könnte man in diesem Issue finden.

2. **Recherche bei vorhandenem Code
    Demnächst kam es zu dem Zeitpunkt, an dem ein Teil vom Code veröffentlich wurde.**

    Nach der Veröffentlichung eines Teils des Codes, gab es von vielen Experten einige Fragen an dem Datenschutzaspekt. Dann haben wir einige Artikel bezüglich die verschiedenen Ansichten auf die möglichen Lücken im Bereich Datensicherheit gelesen. Hier sind einige aufgelistet. Wir haben auch versucht die Kritik zu verstehen und zu geregeln oder widersprechen: 

    * [#223](https://github.com/corona-warn-app/cwa-documentation/issues/223)
   * [#273](https://github.com/corona-warn-app/cwa-documentation/issues/273)

   Einige nutzer haben auch auf mehr Transperenz bei der Risikoberechnung geboten: 
   
   * [#338](https://github.com/corona-warn-app/cwa-documentation/issues/338)

    Ein anderes sehr wichtiges Problem mit dem Datenschutz und Transperenz Aspekten war, dass obwohl, dass das App als "open source" bezeichnet wurde, war es bis zu dem Zeitpunkt des Veröffentlichens nicht möglich, dies getestet zu werden, da es eine GMS Exposure API Whitelisting gab.

    * [#214](https://github.com/corona-warn-app/cwa-documentation/issues/214)

    Dazu könnte man mehr Information bei dem Team "Exposure API" finden.

3. **Recherche nach der Veröffentlichung des Apps.**

    Dann war unseres "Datenschutz Team" gegründet. Wir haben uns als erstens viel mit dem Datenschutzerklärung des offiziellen App beschäftigt. 

    Erstmal haben wir:
    * [Dominique Machuletz* and Rainer Böhme, Multiple Purposes, Multiple Problems:
    A User Study of Consent Dialogs after GDPR](https://petsymposium.org/2020/files/papers/issue2/popets-2020-0037.pdf)
    * [Ghazinour, K. and Albalawi, T., 2016, August. A usability study on the privacy policy visualization model. In 2016 IEEE 14th Intl Conf on Dependable, Autonomic and Secure Computing, 14th Intl Conf on Pervasive Intelligence and Computing, 2nd Intl Conf on Big Data Intelligence and Computing and Cyber Science and Technology Congress (DASC/PiCom/DataCom/CyberSciTech) (pp. 578-585). IEEE.](https://ieeexplore.ieee.org/abstract/document/7588905) 
    * [Clarke, N., Furnell, S., Angulo, J., Fischer‐Hübner, S., Wästlund, E. and Pulls, T., 2012. Towards usable privacy policy display and management. Information Management & Computer Security.](https://www.emerald.com/insight/content/doi/10.1108/09685221211219155/full/html?casa_token=-yqn0Wj8w2wAAAAA:gj8sWdbJqaMdmvF2l96g6LeZGQue58yD505J3wWyuwQY2v_RpVqLnPBMJfAZ_xyiGoGTwrKivhjOWZKzUnqIOfQ3Ja-3CSXrXPSDgAR2yERiKDaV3kE) 
  
  gelesen und darauf die Erkentnisse mit dem offiziellen Datenschutzerklärung ([DE Version](https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/assets/privacy_de.html),[EN Version](https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/assets/privacy_en.html)) des Corona Warn Apps verglichen. ([#149](https://github.com/FUB-HCC/20-SWP-CodingOpenness/issues/149))

  ""
  
## *Current Implementation*
*Many users are still struggling with privacy concerns when using the app. However, current visualization and structure of the privacy policy feel like "infinity scrolling" and the overall plain visualization does not attract user to read the privacy policy in its full length. Status now, there are no unfoldable areas, highlighted areas, supporting links for explanation, icons or even images/models are used.*   

## *Suggested Enhancement*
*Make the the dry text of privacy policy more appealing in order to gain more transparency, trust and understanding towards the user. Research showed that the usage of a variety of "telling" icons, models and diagrams can help users to understand PP better and let users
recognize which service providers are requesting which kind of data. Also adding the author`s credentials or links to the legal texts of the General Data Protection Regulation (GDPR) can have a positive impact.*

## *Expected Benefits*
*Create a **better understanding** for the user and thus **increase acceptance** for the app. Furthermore, **increase willingness** (of people who are still sceptical) **to install the app** by by advertising and pre-reading the privacy policy directly on the website.*

""

Hier könnte man unsere Zusammenarbeit nachvollziehen [#149](https://github.com/FUB-HCC/20-SWP-CodingOpenness/issues/149). Daraus ist diese Issue in der offizielle Repository entstanden als Verbesserungswunsch [#16](https://github.com/corona-warn-app/cwa-wishlist/issues/16).

Wir haben uns entschieden, unsere Vorschläge mit einem Prototyp zu erstellen. [#185](https://github.com/FUB-HCC/20-SWP-CodingOpenness/issues/185)

Wir hatten auch die Anmerkung, dass die Datenschutzerklärung zu lang gemacht wurde, was eigentlich dazu führt, dass die Größe des Texts den Nutzer erschreckt. Wir haben dann uns entschieden eine Alternative vorzubereiten und haben uns geeinigt, dass das Aufklappen von verschiedenen Aspekten der Datenschutzerklärung (sodass der Nutzer nur die Aspekten sehen könnte, die ihn interessieren). Unsere Arbeit dazu kann hier nachgefolgt werden . [#168](https://github.com/FUB-HCC/20-SWP-CodingOpenness/issues/168)

Noch ein  Verständnisaspekt der Datenschutzerklärung ist die verwendete formale Sprache und die Gelegenheit das Text in verschiedenen Sprachen zu implementieren, da es auch von den verschiedenen in Deutschland lebenden Nationalitäten verstanden wurde. Diese wurde in dem vorherigen "Team Technik" besprochen und es gibt auch für die Sprachenunterstützung eine offizielle Issue in dem offiziellen Repository, dass in der Zukunft für die Erweiterung mit mehreren Sprachen verantwortlich ist. [#22](https://github.com/corona-warn-app/cwa-wishlist/issues/22). Momentan gibt es [EN](https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/assets/privacy_en.html), [DE](https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/assets/privacy_de.html), [TR](https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/assets/privacy_tr.html) Version zu dem App.

Damit haben wir die Hauptaspekte unserer Recherche erledigt und besprochen.

**Comment by linuxhelf** [comment]
Ich finde Wiki-Page(s) einen guten Vorschlag und nur die Zusammenfassung mit Links auf die Webseite.
Ich habe mal ein paar Seiten erstellt und auch rechts in der Wikistruktur verlinkt:
  * [Data Privacy](https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki//Data-Privacy)
    * [Research](https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki//Data-Privacy%3A-Research)
    * [Prototype](https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki//Data-Privacy%3A-Prototype)
    * [Implementation](https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki//Data-Privacy%3A-Implementation)

den Implementationsvorschlag + die Researchzusammenfassung von @kraleva habe ich schonmal reinkopiert

**Comment by linuxhelf** [comment]
ich habe die Übersichts- und Prototypseite mal mit ein paar Sätzen befüllt, damit sie nicht so leer sind.

**Comment by julizet** [comment]
Ihr habt ja schon einen Menge getan!

Ich lese nochmal Lektorat für die bereits veröffentlichten Wiki-Pages und würde schauen, dass die Formulierungen und die Formattierung passt. 
Zudem: da Felix sich noch nicht gemeldet hat und Claas/Linux den Prototypen schon auf der Website eingebunden haben und wir nur noch auf den confirm des PR warten, würde ich mich über eine kleine Doku der Aktivitäten im offiziellem Repo kümmern.

So ist auch direkt klar, wer was zur Präsentation sagt

**Comment by Erdnaf** [comment]
Plan für die Präsentation:

- Vergleich mit Einleitung (Webseite mit Vergleich der Ansätze zeigen) / @molpremotone 
- Recherche (Wiki Seite zeigen) / @kraleva 
- Prototyp / @julizet 
- Implementierung / @linuxhelf 
- Ausblick / @Erdanf 

Screensharing:
@julizet 
Ersatz:
@linuxhelf
