### ISSUE TITLE
Can't hit back to get to the last view in the website

### ISSUE THREAD

**Issue by omerhod** [FUB-HCC/20-SWP-CodingOpenness#85]
# Bounty
- although we're dealing with a single-page website, we could introduce different url's to different parts of the app in order to let the user the ability to use their native browser's `back` functionality.
- ~~make use of the History API to allow users use their browser's back functionality~~
- Fix by implementing React Router and making component navigation routable.

## Gain for the project
better UIUX

## Roles

bounty worker: @oussab  
bounty reviewer: @Hod04 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by metaspice** [comment]
***Status Update:***

This issue is being actively fixed under the branch: https://github.com/FUB-HCC/20-SWP-CodingOpenness/tree/website/feat/routing

- Routing is now working as expected. 
- ***Issue:*** When going back a page, the button that refers to the last page stays activated since the state value is used to determine whether a button is visibly active or not.
Going back a page does not reset the state value nor does it change the value of the history path (which I get by using "history.location.pathname" where history is the object imported from the "history" package). 
- **Missing:** Routing under the "Ansätze" page (for each approach). Doable but waiting to fix above issue before implementing routing for this page.
